# ate
# 0
sh repeat_non_bert.sh 0 0-ASOTEDataRest14-0,0-ASOTEDataRest14-1,0-ASOTEDataRest14-2,0-ASOTEDataRest14-3,0-ASOTEDataRest14-4 nlp_tasks/absa/mining_opinions/sequence_labeling/ate_bootstrap.py --embedding_filepath glove.840B.300d.txt --current_dataset ASOTEDataRest14 --data_type common --model_name NerLstm --train True --evaluate True --predict False --predict_test True --crf False > ate.0-ASOTEDataRest14-0.log 2>&1 &

sh repeat_non_bert.sh 0 0-ASOTEDataLapt14-0,0-ASOTEDataLapt14-1,0-ASOTEDataLapt14-2,0-ASOTEDataLapt14-3,0-ASOTEDataLapt14-4 nlp_tasks/absa/mining_opinions/sequence_labeling/ate_bootstrap.py --embedding_filepath glove.840B.300d.txt --current_dataset ASOTEDataLapt14 --data_type common --model_name NerLstm --train True --evaluate True --predict False --predict_test True --crf False > ate.0-ASOTEDataLapt14-0.log 2>&1 &

sh repeat_non_bert.sh 0 0-ASOTEDataRest15-0,0-ASOTEDataRest15-1,0-ASOTEDataRest15-2,0-ASOTEDataRest15-3,0-ASOTEDataRest15-4 nlp_tasks/absa/mining_opinions/sequence_labeling/ate_bootstrap.py --embedding_filepath glove.840B.300d.txt --current_dataset ASOTEDataRest15 --data_type common --model_name NerLstm --train True --evaluate True --predict False --predict_test True --crf False > ate.0-ASOTEDataRest15-0.log 2>&1 &

sh repeat_non_bert.sh 0 0-ASOTEDataRest16-0,0-ASOTEDataRest16-1,0-ASOTEDataRest16-2,0-ASOTEDataRest16-3,0-ASOTEDataRest16-4 nlp_tasks/absa/mining_opinions/sequence_labeling/ate_bootstrap.py --embedding_filepath glove.840B.300d.txt --current_dataset ASOTEDataRest16 --data_type common --model_name NerLstm --train True --evaluate True --predict False --predict_test True --crf False > ate.0-ASOTEDataRest16-0.log 2>&1 &

# 1
sh repeat_non_bert.sh 1 1-ASOTEDataRest14-0,1-ASOTEDataRest14-1,1-ASOTEDataRest14-2,1-ASOTEDataRest14-3,1-ASOTEDataRest14-4 nlp_tasks/absa/mining_opinions/sequence_labeling/ate_bootstrap.py --embedding_filepath glove.840B.300d.txt --bert_file_path bert-base-uncased.tar.gz --bert_vocab_file_path uncased_L-12_H-768_A-12/vocab.txt --current_dataset ASOTEDataRest14 --data_type common_bert --model_name NerBert --train True --evaluate True --predict False --predict_test True --crf False > ate.1-ASOTEDataRest14-0.log 2>&1 &

sh repeat_non_bert.sh 1 1-ASOTEDataLapt14-0,1-ASOTEDataLapt14-1,1-ASOTEDataLapt14-2,1-ASOTEDataLapt14-3,1-ASOTEDataLapt14-4 nlp_tasks/absa/mining_opinions/sequence_labeling/ate_bootstrap.py --embedding_filepath glove.840B.300d.txt --bert_file_path bert-base-uncased.tar.gz --bert_vocab_file_path uncased_L-12_H-768_A-12/vocab.txt --current_dataset ASOTEDataLapt14 --data_type common_bert --model_name NerBert --train True --evaluate True --predict False --predict_test True --crf False > ate.1-ASOTEDataLapt14-0.log 2>&1 &

sh repeat_non_bert.sh 2 1-ASOTEDataRest15-0,1-ASOTEDataRest15-1,1-ASOTEDataRest15-2,1-ASOTEDataRest15-3,1-ASOTEDataRest15-4 nlp_tasks/absa/mining_opinions/sequence_labeling/ate_bootstrap.py --embedding_filepath glove.840B.300d.txt --bert_file_path bert-base-uncased.tar.gz --bert_vocab_file_path uncased_L-12_H-768_A-12/vocab.txt --current_dataset ASOTEDataRest15 --data_type common_bert --model_name NerBert --train True --evaluate True --predict False --predict_test True --crf False > ate.1-ASOTEDataRest15-0.log 2>&1 &

sh repeat_non_bert.sh 2 1-ASOTEDataRest16-0,1-ASOTEDataRest16-1,1-ASOTEDataRest16-2,1-ASOTEDataRest16-3,1-ASOTEDataRest16-4 nlp_tasks/absa/mining_opinions/sequence_labeling/ate_bootstrap.py --embedding_filepath glove.840B.300d.txt --bert_file_path bert-base-uncased.tar.gz --bert_vocab_file_path uncased_L-12_H-768_A-12/vocab.txt --current_dataset ASOTEDataRest16 --data_type common_bert --model_name NerBert --train True --evaluate True --predict False --predict_test True --crf False > ate.1-ASOTEDataRest16-0.log 2>&1 &

# 4
sh repeat_non_bert.sh 7 4-ASOTEDataRest14-0,4-ASOTEDataRest14-1,4-ASOTEDataRest14-2,4-ASOTEDataRest14-3,4-ASOTEDataRest14-4 nlp_tasks/absa/mining_opinions/sequence_labeling/ate_bootstrap.py --embedding_filepath glove.840B.300d.txt --bert_file_path bert-base-uncased.tar.gz --bert_vocab_file_path uncased_L-12_H-768_A-12/vocab.txt --current_dataset ASOTEDataRest14 --data_type common_bert --model_name NerBert --train True --evaluate True --predict False --predict_test True --crf False --fixed_bert False > ate.4-ASOTEDataRest14-0.log 2>&1 &

sh repeat_non_bert.sh 2 4-ASOTEDataLapt14-0,4-ASOTEDataLapt14-1,4-ASOTEDataLapt14-2,4-ASOTEDataLapt14-3,4-ASOTEDataLapt14-4 nlp_tasks/absa/mining_opinions/sequence_labeling/ate_bootstrap.py --embedding_filepath glove.840B.300d.txt --bert_file_path bert-base-uncased.tar.gz --bert_vocab_file_path uncased_L-12_H-768_A-12/vocab.txt --current_dataset ASOTEDataLapt14 --data_type common_bert --model_name NerBert --train True --evaluate True --predict False --predict_test True --crf False --fixed_bert False > ate.4-ASOTEDataLapt14-0.log 2>&1 &

sh repeat_non_bert.sh 3 4-ASOTEDataRest15-0,4-ASOTEDataRest15-1,4-ASOTEDataRest15-2,4-ASOTEDataRest15-3,4-ASOTEDataRest15-4 nlp_tasks/absa/mining_opinions/sequence_labeling/ate_bootstrap.py --embedding_filepath glove.840B.300d.txt --bert_file_path bert-base-uncased.tar.gz --bert_vocab_file_path uncased_L-12_H-768_A-12/vocab.txt --current_dataset ASOTEDataRest15 --data_type common_bert --model_name NerBert --train True --evaluate True --predict False --predict_test True --crf False --fixed_bert False > ate.4-ASOTEDataRest15-0.log 2>&1 &

sh repeat_non_bert.sh 3 4-ASOTEDataRest16-0,4-ASOTEDataRest16-1,4-ASOTEDataRest16-2,4-ASOTEDataRest16-3,4-ASOTEDataRest16-4 nlp_tasks/absa/mining_opinions/sequence_labeling/ate_bootstrap.py --embedding_filepath glove.840B.300d.txt --bert_file_path bert-base-uncased.tar.gz --bert_vocab_file_path uncased_L-12_H-768_A-12/vocab.txt --current_dataset ASOTEDataRest16 --data_type common_bert --model_name NerBert --train True --evaluate True --predict False --predict_test True --crf False --fixed_bert False > ate.4-ASOTEDataRest16-0.log 2>&1 &