# mil-AGF (ATE, TOWE_ATSA_jointly) bilstm 0 36
sh run.sh asote_pipeline_evaluation_bootstrap_for_mil.py --current_dataset ASOTEDataRest14 --ate_result_filepath_template absa/ate/ASOTEDataRest14/common/model_name_NerLstm-include_conflict_False.0-ASOTEDataRest14-%d/1571400646/models/result_of_predicting_test.txt --so_result_filepath_template absa/aso/ASOTEDataRest14/common_mil/model_name_MILForASO.36-ASOTEDataRest14-%d/1571400646/models/result_of_predicting_test.txt

sh run.sh asote_pipeline_evaluation_bootstrap_for_mil.py --current_dataset ASOTEDataLapt14 --ate_result_filepath_template absa/ate/ASOTEDataLapt14/common/model_name_NerLstm-include_conflict_False.0-ASOTEDataLapt14-%d/1571400646/models/result_of_predicting_test.txt --so_result_filepath_template absa/aso/ASOTEDataLapt14/common_mil/model_name_MILForASO.36-ASOTEDataLapt14-%d/1571400646/models/result_of_predicting_test.txt

sh run.sh asote_pipeline_evaluation_bootstrap_for_mil.py --current_dataset ASOTEDataRest15 --ate_result_filepath_template absa/ate/ASOTEDataRest15/common/model_name_NerLstm-include_conflict_False.0-ASOTEDataRest15-%d/1571400646/models/result_of_predicting_test.txt --so_result_filepath_template absa/aso/ASOTEDataRest15/common_mil/model_name_MILForASO.36-ASOTEDataRest15-%d/1571400646/models/result_of_predicting_test.txt

sh run.sh asote_pipeline_evaluation_bootstrap_for_mil.py --current_dataset ASOTEDataRest16 --ate_result_filepath_template absa/ate/ASOTEDataRest16/common/model_name_NerLstm-include_conflict_False.0-ASOTEDataRest16-%d/1571400646/models/result_of_predicting_test.txt --so_result_filepath_template absa/aso/ASOTEDataRest16/common_mil/model_name_MILForASO.36-ASOTEDataRest16-%d/1571400646/models/result_of_predicting_test.txt

# mil-AGF (ATE, TOWE_ATSA_jointly) fixed bert 1 4
sh run.sh asote_pipeline_evaluation_bootstrap_for_mil.py --current_dataset ASOTEDataRest14 --ate_result_filepath_template absa/ate/ASOTEDataRest14/common_bert/model_name_NerBert-include_conflict_False.1-ASOTEDataRest14-%d/1571400646/models/result_of_predicting_test.txt --so_result_filepath_template absa/aso/ASOTEDataRest14/common_mil_bert/model_name_MILForASOBert.4-ASOTEDataRest14-%d/1571400646/models/result_of_predicting_test.txt

sh run.sh asote_pipeline_evaluation_bootstrap_for_mil.py --current_dataset ASOTEDataLapt14 --ate_result_filepath_template absa/ate/ASOTEDataLapt14/common_bert/model_name_NerBert-include_conflict_False.1-ASOTEDataLapt14-%d/1571400646/models/result_of_predicting_test.txt --so_result_filepath_template absa/aso/ASOTEDataLapt14/common_mil_bert/model_name_MILForASOBert.4-ASOTEDataLapt14-%d/1571400646/models/result_of_predicting_test.txt

sh run.sh asote_pipeline_evaluation_bootstrap_for_mil.py --current_dataset ASOTEDataRest15 --ate_result_filepath_template absa/ate/ASOTEDataRest15/common_bert/model_name_NerBert-include_conflict_False.1-ASOTEDataRest15-%d/1571400646/models/result_of_predicting_test.txt --so_result_filepath_template absa/aso/ASOTEDataRest15/common_mil_bert/model_name_MILForASOBert.4-ASOTEDataRest15-%d/1571400646/models/result_of_predicting_test.txt

sh run.sh asote_pipeline_evaluation_bootstrap_for_mil.py --current_dataset ASOTEDataRest16 --ate_result_filepath_template absa/ate/ASOTEDataRest16/common_bert/model_name_NerBert-include_conflict_False.1-ASOTEDataRest16-%d/1571400646/models/result_of_predicting_test.txt --so_result_filepath_template absa/aso/ASOTEDataRest16/common_mil_bert/model_name_MILForASOBert.4-ASOTEDataRest16-%d/1571400646/models/result_of_predicting_test.txt

# mil-AGF (ATE, TOWE_ATSA_jointly) finetune bert 4 10
sh run.sh asote_pipeline_evaluation_bootstrap_for_mil.py --current_dataset ASOTEDataRest14 --ate_result_filepath_template absa/ate/ASOTEDataRest14/common_bert/model_name_NerBert-include_conflict_False.4-ASOTEDataRest14-%d/1571400646/models/result_of_predicting_test.txt --so_result_filepath_template absa/aso/ASOTEDataRest14/common_mil_bert/model_name_MILForASOBert.10-ASOTEDataRest14-%d/1571400646/models/result_of_predicting_test.txt

sh run.sh asote_pipeline_evaluation_bootstrap_for_mil.py --current_dataset ASOTEDataLapt14 --ate_result_filepath_template absa/ate/ASOTEDataLapt14/common_bert/model_name_NerBert-include_conflict_False.4-ASOTEDataLapt14-%d/1571400646/models/result_of_predicting_test.txt --so_result_filepath_template absa/aso/ASOTEDataLapt14/common_mil_bert/model_name_MILForASOBert.10-ASOTEDataLapt14-%d/1571400646/models/result_of_predicting_test.txt

sh run.sh asote_pipeline_evaluation_bootstrap_for_mil.py --current_dataset ASOTEDataRest15 --ate_result_filepath_template absa/ate/ASOTEDataRest15/common_bert/model_name_NerBert-include_conflict_False.4-ASOTEDataRest15-%d/1571400646/models/result_of_predicting_test.txt --so_result_filepath_template absa/aso/ASOTEDataRest15/common_mil_bert/model_name_MILForASOBert.10-ASOTEDataRest15-%d/1571400646/models/result_of_predicting_test.txt

sh run.sh asote_pipeline_evaluation_bootstrap_for_mil.py --current_dataset ASOTEDataRest16 --ate_result_filepath_template absa/ate/ASOTEDataRest16/common_bert/model_name_NerBert-include_conflict_False.4-ASOTEDataRest16-%d/1571400646/models/result_of_predicting_test.txt --so_result_filepath_template absa/aso/ASOTEDataRest16/common_mil_bert/model_name_MILForASOBert.10-ASOTEDataRest16-%d/1571400646/models/result_of_predicting_test.txt

# Unified-tag-AGF (ATE, TOWE_TOSC_jointly) bilstm 0 36
sh run.sh asote_pipeline_evaluation_bootstrap_for_mil.py --current_dataset ASOTEDataRest14 --ate_result_filepath_template absa/ate/ASOTEDataRest14/common/model_name_NerLstm-include_conflict_False.0-ASOTEDataRest14-%d/1571400646/models/result_of_predicting_test.txt --so_result_filepath_template absa/aso/ASOTEDataRest14/common_unified_tag/model_name_AsoTermModel.36-ASOTEDataRest14-%d/1571400646/models/result_of_predicting_test.txt

sh run.sh asote_pipeline_evaluation_bootstrap_for_mil.py --current_dataset ASOTEDataLapt14 --ate_result_filepath_template absa/ate/ASOTEDataLapt14/common/model_name_NerLstm-include_conflict_False.0-ASOTEDataLapt14-%d/1571400646/models/result_of_predicting_test.txt --so_result_filepath_template absa/aso/ASOTEDataLapt14/common_unified_tag/model_name_AsoTermModel.36-ASOTEDataLapt14-%d/1571400646/models/result_of_predicting_test.txt

sh run.sh asote_pipeline_evaluation_bootstrap_for_mil.py --current_dataset ASOTEDataRest15 --ate_result_filepath_template absa/ate/ASOTEDataRest15/common/model_name_NerLstm-include_conflict_False.0-ASOTEDataRest15-%d/1571400646/models/result_of_predicting_test.txt --so_result_filepath_template absa/aso/ASOTEDataRest15/common_unified_tag/model_name_AsoTermModel.36-ASOTEDataRest15-%d/1571400646/models/result_of_predicting_test.txt

sh run.sh asote_pipeline_evaluation_bootstrap_for_mil.py --current_dataset ASOTEDataRest16 --ate_result_filepath_template absa/ate/ASOTEDataRest16/common/model_name_NerLstm-include_conflict_False.0-ASOTEDataRest16-%d/1571400646/models/result_of_predicting_test.txt --so_result_filepath_template absa/aso/ASOTEDataRest16/common_unified_tag/model_name_AsoTermModel.36-ASOTEDataRest16-%d/1571400646/models/result_of_predicting_test.txt

# Unified-tag-AGF (ATE, TOWE_TOSC_jointly) fixed bert 1 4
sh run.sh asote_pipeline_evaluation_bootstrap_for_mil.py --current_dataset ASOTEDataRest14 --ate_result_filepath_template absa/ate/ASOTEDataRest14/common_bert/model_name_NerBert-include_conflict_False.1-ASOTEDataRest14-%d/1571400646/models/result_of_predicting_test.txt --so_result_filepath_template absa/aso/ASOTEDataRest14/common_unified_tag_bert/model_name_AsoTermModelBert.4-ASOTEDataRest14-%d/1571400646/models/result_of_predicting_test.txt

sh run.sh asote_pipeline_evaluation_bootstrap_for_mil.py --current_dataset ASOTEDataLapt14 --ate_result_filepath_template absa/ate/ASOTEDataLapt14/common_bert/model_name_NerBert-include_conflict_False.1-ASOTEDataLapt14-%d/1571400646/models/result_of_predicting_test.txt --so_result_filepath_template absa/aso/ASOTEDataLapt14/common_unified_tag_bert/model_name_AsoTermModelBert.4-ASOTEDataLapt14-%d/1571400646/models/result_of_predicting_test.txt

sh run.sh asote_pipeline_evaluation_bootstrap_for_mil.py --current_dataset ASOTEDataRest15 --ate_result_filepath_template absa/ate/ASOTEDataRest15/common_bert/model_name_NerBert-include_conflict_False.1-ASOTEDataRest15-%d/1571400646/models/result_of_predicting_test.txt --so_result_filepath_template absa/aso/ASOTEDataRest15/common_unified_tag_bert/model_name_AsoTermModelBert.4-ASOTEDataRest15-%d/1571400646/models/result_of_predicting_test.txt

sh run.sh asote_pipeline_evaluation_bootstrap_for_mil.py --current_dataset ASOTEDataRest16 --ate_result_filepath_template absa/ate/ASOTEDataRest16/common_bert/model_name_NerBert-include_conflict_False.1-ASOTEDataRest16-%d/1571400646/models/result_of_predicting_test.txt --so_result_filepath_template absa/aso/ASOTEDataRest16/common_unified_tag_bert/model_name_AsoTermModelBert.4-ASOTEDataRest16-%d/1571400646/models/result_of_predicting_test.txt

# Unified-tag-AGF (ATE, TOWE_TOSC_jointly) finetune bert 4 10
sh run.sh asote_pipeline_evaluation_bootstrap_for_mil.py --current_dataset ASOTEDataRest14 --ate_result_filepath_template absa/ate/ASOTEDataRest14/common_bert/model_name_NerBert-include_conflict_False.4-ASOTEDataRest14-%d/1571400646/models/result_of_predicting_test.txt --so_result_filepath_template absa/aso/ASOTEDataRest14/common_unified_tag_bert/model_name_AsoTermModelBert.10-ASOTEDataRest14-%d/1571400646/models/result_of_predicting_test.txt

sh run.sh asote_pipeline_evaluation_bootstrap_for_mil.py --current_dataset ASOTEDataLapt14 --ate_result_filepath_template absa/ate/ASOTEDataLapt14/common_bert/model_name_NerBert-include_conflict_False.4-ASOTEDataLapt14-%d/1571400646/models/result_of_predicting_test.txt --so_result_filepath_template absa/aso/ASOTEDataLapt14/common_unified_tag_bert/model_name_AsoTermModelBert.10-ASOTEDataLapt14-%d/1571400646/models/result_of_predicting_test.txt

sh run.sh asote_pipeline_evaluation_bootstrap_for_mil.py --current_dataset ASOTEDataRest15 --ate_result_filepath_template absa/ate/ASOTEDataRest15/common_bert/model_name_NerBert-include_conflict_False.4-ASOTEDataRest15-%d/1571400646/models/result_of_predicting_test.txt --so_result_filepath_template absa/aso/ASOTEDataRest15/common_unified_tag_bert/model_name_AsoTermModelBert.10-ASOTEDataRest15-%d/1571400646/models/result_of_predicting_test.txt

sh run.sh asote_pipeline_evaluation_bootstrap_for_mil.py --current_dataset ASOTEDataRest16 --ate_result_filepath_template absa/ate/ASOTEDataRest16/common_bert/model_name_NerBert-include_conflict_False.4-ASOTEDataRest16-%d/1571400646/models/result_of_predicting_test.txt --so_result_filepath_template absa/aso/ASOTEDataRest16/common_unified_tag_bert/model_name_AsoTermModelBert.10-ASOTEDataRest16-%d/1571400646/models/result_of_predicting_test.txt

# pipeline-AGF (ATE, TOWE, TOSC) bilstm 0 0 9
sh run.sh asote_pipeline_evaluation_bootstrap.py --current_dataset ASOTEDataRest14 --ate_result_filepath_template absa/ate/ASOTEDataRest14/common/model_name_NerLstm-include_conflict_False.0-ASOTEDataRest14-%d/1571400646/models/result_of_predicting_test.txt --towe_result_filepath_template absa/towe/ASOTEDataRest14/common/model_name_TermBiLSTM-include_conflict_False.0-ASOTEDataRest14-%d/1571400646/models/result_of_predicting_test.txt --tosc_result_filepath_template absa/tosc/ASOTEDataRest14/common/model_name_LSTM.9-ASOTEDataRest14-%d/1571400646/models/result_of_predicting_test.txt

sh run.sh asote_pipeline_evaluation_bootstrap.py --current_dataset ASOTEDataLapt14 --ate_result_filepath_template absa/ate/ASOTEDataLapt14/common/model_name_NerLstm-include_conflict_False.0-ASOTEDataLapt14-%d/1571400646/models/result_of_predicting_test.txt --towe_result_filepath_template absa/towe/ASOTEDataLapt14/common/model_name_TermBiLSTM-include_conflict_False.0-ASOTEDataLapt14-%d/1571400646/models/result_of_predicting_test.txt --tosc_result_filepath_template absa/tosc/ASOTEDataLapt14/common/model_name_LSTM.9-ASOTEDataLapt14-%d/1571400646/models/result_of_predicting_test.txt

sh run.sh asote_pipeline_evaluation_bootstrap.py --current_dataset ASOTEDataRest15 --ate_result_filepath_template absa/ate/ASOTEDataRest15/common/model_name_NerLstm-include_conflict_False.0-ASOTEDataRest15-%d/1571400646/models/result_of_predicting_test.txt --towe_result_filepath_template absa/towe/ASOTEDataRest15/common/model_name_TermBiLSTM-include_conflict_False.0-ASOTEDataRest15-%d/1571400646/models/result_of_predicting_test.txt --tosc_result_filepath_template absa/tosc/ASOTEDataRest15/common/model_name_LSTM.9-ASOTEDataRest15-%d/1571400646/models/result_of_predicting_test.txt

sh run.sh asote_pipeline_evaluation_bootstrap.py --current_dataset ASOTEDataRest16 --ate_result_filepath_template absa/ate/ASOTEDataRest16/common/model_name_NerLstm-include_conflict_False.0-ASOTEDataRest16-%d/1571400646/models/result_of_predicting_test.txt --towe_result_filepath_template absa/towe/ASOTEDataRest16/common/model_name_TermBiLSTM-include_conflict_False.0-ASOTEDataRest16-%d/1571400646/models/result_of_predicting_test.txt --tosc_result_filepath_template absa/tosc/ASOTEDataRest16/common/model_name_LSTM.9-ASOTEDataRest16-%d/1571400646/models/result_of_predicting_test.txt

# pipeline-AGF (ATE, TOWE, TOSC) fixed bert 1 2 13
sh run.sh asote_pipeline_evaluation_bootstrap.py --current_dataset ASOTEDataRest14 --ate_result_filepath_template absa/ate/ASOTEDataRest14/common_bert/model_name_NerBert-include_conflict_False.1-ASOTEDataRest14-%d/1571400646/models/result_of_predicting_test.txt --towe_result_filepath_template absa/towe/ASOTEDataRest14/common_bert/model_name_TermBert-include_conflict_False.2-ASOTEDataRest14-%d/1571400646/models/result_of_predicting_test.txt --tosc_result_filepath_template absa/tosc/ASOTEDataRest14/bert_single/model_name_bert.13-ASOTEDataRest14-%d/1571400646/models/result_of_predicting_test.txt

sh run.sh asote_pipeline_evaluation_bootstrap.py --current_dataset ASOTEDataLapt14 --ate_result_filepath_template absa/ate/ASOTEDataLapt14/common_bert/model_name_NerBert-include_conflict_False.1-ASOTEDataLapt14-%d/1571400646/models/result_of_predicting_test.txt --towe_result_filepath_template absa/towe/ASOTEDataLapt14/common_bert/model_name_TermBert-include_conflict_False.2-ASOTEDataLapt14-%d/1571400646/models/result_of_predicting_test.txt --tosc_result_filepath_template absa/tosc/ASOTEDataLapt14/bert_single/model_name_bert.13-ASOTEDataLapt14-%d/1571400646/models/result_of_predicting_test.txt

sh run.sh asote_pipeline_evaluation_bootstrap.py --current_dataset ASOTEDataRest15 --ate_result_filepath_template absa/ate/ASOTEDataRest15/common_bert/model_name_NerBert-include_conflict_False.1-ASOTEDataRest15-%d/1571400646/models/result_of_predicting_test.txt --towe_result_filepath_template absa/towe/ASOTEDataRest15/common_bert/model_name_TermBert-include_conflict_False.2-ASOTEDataRest15-%d/1571400646/models/result_of_predicting_test.txt --tosc_result_filepath_template absa/tosc/ASOTEDataRest15/bert_single/model_name_bert.13-ASOTEDataRest15-%d/1571400646/models/result_of_predicting_test.txt

sh run.sh asote_pipeline_evaluation_bootstrap.py --current_dataset ASOTEDataRest16 --ate_result_filepath_template absa/ate/ASOTEDataRest16/common_bert/model_name_NerBert-include_conflict_False.1-ASOTEDataRest16-%d/1571400646/models/result_of_predicting_test.txt --towe_result_filepath_template absa/towe/ASOTEDataRest16/common_bert/model_name_TermBert-include_conflict_False.2-ASOTEDataRest16-%d/1571400646/models/result_of_predicting_test.txt --tosc_result_filepath_template absa/tosc/ASOTEDataRest16/bert_single/model_name_bert.13-ASOTEDataRest16-%d/1571400646/models/result_of_predicting_test.txt

# pipeline-AGF (ATE, TOWE, TOSC) finetune bert 4 8 2
sh run.sh asote_pipeline_evaluation_bootstrap.py --current_dataset ASOTEDataRest14 --ate_result_filepath_template absa/ate/ASOTEDataRest14/common_bert/model_name_NerBert-include_conflict_False.4-ASOTEDataRest14-%d/1571400646/models/result_of_predicting_test.txt --towe_result_filepath_template absa/towe/ASOTEDataRest14/common_bert/model_name_TermBert-include_conflict_False.8-ASOTEDataRest14-%d/1571400646/models/result_of_predicting_test.txt --tosc_result_filepath_template absa/tosc/ASOTEDataRest14/bert/model_name_bert.2-ASOTEDataRest14-%d/1571400646/models/result_of_predicting_test.txt

sh run.sh asote_pipeline_evaluation_bootstrap.py --current_dataset ASOTEDataLapt14 --ate_result_filepath_template absa/ate/ASOTEDataLapt14/common_bert/model_name_NerBert-include_conflict_False.4-ASOTEDataLapt14-%d/1571400646/models/result_of_predicting_test.txt --towe_result_filepath_template absa/towe/ASOTEDataLapt14/common_bert/model_name_TermBert-include_conflict_False.8-ASOTEDataLapt14-%d/1571400646/models/result_of_predicting_test.txt --tosc_result_filepath_template absa/tosc/ASOTEDataLapt14/bert/model_name_bert.2-ASOTEDataLapt14-%d/1571400646/models/result_of_predicting_test.txt

sh run.sh asote_pipeline_evaluation_bootstrap.py --current_dataset ASOTEDataRest15 --ate_result_filepath_template absa/ate/ASOTEDataRest15/common_bert/model_name_NerBert-include_conflict_False.4-ASOTEDataRest15-%d/1571400646/models/result_of_predicting_test.txt --towe_result_filepath_template absa/towe/ASOTEDataRest15/common_bert/model_name_TermBert-include_conflict_False.8-ASOTEDataRest15-%d/1571400646/models/result_of_predicting_test.txt --tosc_result_filepath_template absa/tosc/ASOTEDataRest15/bert/model_name_bert.2-ASOTEDataRest15-%d/1571400646/models/result_of_predicting_test.txt

sh run.sh asote_pipeline_evaluation_bootstrap.py --current_dataset ASOTEDataRest16 --ate_result_filepath_template absa/ate/ASOTEDataRest16/common_bert/model_name_NerBert-include_conflict_False.4-ASOTEDataRest16-%d/1571400646/models/result_of_predicting_test.txt --towe_result_filepath_template absa/towe/ASOTEDataRest16/common_bert/model_name_TermBert-include_conflict_False.8-ASOTEDataRest16-%d/1571400646/models/result_of_predicting_test.txt --tosc_result_filepath_template absa/tosc/ASOTEDataRest16/bert/model_name_bert.2-ASOTEDataRest16-%d/1571400646/models/result_of_predicting_test.txt