# 36
sh repeat_non_bert.sh 0 36-ASOTEDataRest14-0,36-ASOTEDataRest14-1,36-ASOTEDataRest14-2,36-ASOTEDataRest14-3,36-ASOTEDataRest14-4 nlp_tasks/absa/mining_opinions/sequence_labeling/aso_bootstrap.py --embedding_filepath glove.840B.300d.txt --current_dataset ASOTEDataRest14 --data_type common_mil --model_name MILForASO --train True --evaluate True --predict False --crf False --position False --same_special_token False --aspect_term_aware True --lstm_layer_num_of_sentiment_specific 0 --sequence_label_attention True --softmax_after_opinion_logit False --validation_metric +opinion_sentiment_f1 --atsa_loss_weight 1 --towe_loss_weight 1 --towe_warmup True > mil_aso.36-ASOTEDataRest14-0.log 2>&1 &

sh repeat_non_bert.sh 0 36-ASOTEDataLapt14-0,36-ASOTEDataLapt14-1,36-ASOTEDataLapt14-2,36-ASOTEDataLapt14-3,36-ASOTEDataLapt14-4 nlp_tasks/absa/mining_opinions/sequence_labeling/aso_bootstrap.py --embedding_filepath glove.840B.300d.txt --current_dataset ASOTEDataLapt14 --data_type common_mil --model_name MILForASO --train True --evaluate True --predict False --crf False --position False --same_special_token False --aspect_term_aware True --lstm_layer_num_of_sentiment_specific 0 --sequence_label_attention True --softmax_after_opinion_logit False --validation_metric +opinion_sentiment_f1 --atsa_loss_weight 1 --towe_loss_weight 1 --towe_warmup True > mil_aso.36-ASOTEDataLapt14-0.log 2>&1 &

sh repeat_non_bert.sh 0 36-ASOTEDataRest15-0,36-ASOTEDataRest15-1,36-ASOTEDataRest15-2,36-ASOTEDataRest15-3,36-ASOTEDataRest15-4 nlp_tasks/absa/mining_opinions/sequence_labeling/aso_bootstrap.py --embedding_filepath glove.840B.300d.txt --current_dataset ASOTEDataRest15 --data_type common_mil --model_name MILForASO --train True --evaluate True --predict False --crf False --position False --same_special_token False --aspect_term_aware True --lstm_layer_num_of_sentiment_specific 0 --sequence_label_attention True --softmax_after_opinion_logit False --validation_metric +opinion_sentiment_f1 --atsa_loss_weight 1 --towe_loss_weight 1 --towe_warmup True > mil_aso.36-ASOTEDataRest15-0.log 2>&1 &

sh repeat_non_bert.sh 0 36-ASOTEDataRest16-0,36-ASOTEDataRest16-1,36-ASOTEDataRest16-2,36-ASOTEDataRest16-3,36-ASOTEDataRest16-4 nlp_tasks/absa/mining_opinions/sequence_labeling/aso_bootstrap.py --embedding_filepath glove.840B.300d.txt --current_dataset ASOTEDataRest16 --data_type common_mil --model_name MILForASO --train True --evaluate True --predict False --crf False --position False --same_special_token False --aspect_term_aware True --lstm_layer_num_of_sentiment_specific 0 --sequence_label_attention True --softmax_after_opinion_logit False --validation_metric +opinion_sentiment_f1  --atsa_loss_weight 1 --towe_loss_weight 1 --towe_warmup True > mil_aso.36-ASOTEDataRest16-0.log 2>&1 &

# 4
sh repeat_non_bert.sh 6 4-ASOTEDataRest14-0,4-ASOTEDataRest14-1,4-ASOTEDataRest14-2,4-ASOTEDataRest14-3,4-ASOTEDataRest14-4 nlp_tasks/absa/mining_opinions/sequence_labeling/aso_bootstrap.py --embedding_filepath glove.840B.300d.txt --bert_file_path bert-base-uncased.tar.gz --bert_vocab_file_path uncased_L-12_H-768_A-12/vocab.txt --current_dataset ASOTEDataRest14 --data_type common_mil_bert --model_name MILForASOBert --train True --evaluate True --predict False --crf False --position False --same_special_token False --aspect_term_aware True --lstm_layer_num_of_sentiment_specific 0 --sequence_label_attention True --softmax_after_opinion_logit False --validation_metric +opinion_sentiment_f1 --atsa_loss_weight 1 --towe_loss_weight 1 --towe_warmup True > mil_aso.4-ASOTEDataRest14-0.log 2>&1 &

sh repeat_non_bert.sh 4 4-ASOTEDataLapt14-0,4-ASOTEDataLapt14-1,4-ASOTEDataLapt14-2,4-ASOTEDataLapt14-3,4-ASOTEDataLapt14-4 nlp_tasks/absa/mining_opinions/sequence_labeling/aso_bootstrap.py --embedding_filepath glove.840B.300d.txt --bert_file_path bert-base-uncased.tar.gz --bert_vocab_file_path uncased_L-12_H-768_A-12/vocab.txt --current_dataset ASOTEDataLapt14 --data_type common_mil_bert --model_name MILForASOBert --train True --evaluate True --predict False --crf False --position False --same_special_token False --aspect_term_aware True --lstm_layer_num_of_sentiment_specific 0 --sequence_label_attention True --softmax_after_opinion_logit False --validation_metric +opinion_sentiment_f1 --atsa_loss_weight 1 --towe_loss_weight 1 --towe_warmup True > mil_aso.4-ASOTEDataLapt14-0.log 2>&1 &

sh repeat_non_bert.sh 5 4-ASOTEDataRest15-0,4-ASOTEDataRest15-1,4-ASOTEDataRest15-2,4-ASOTEDataRest15-3,4-ASOTEDataRest15-4 nlp_tasks/absa/mining_opinions/sequence_labeling/aso_bootstrap.py --embedding_filepath glove.840B.300d.txt --bert_file_path bert-base-uncased.tar.gz --bert_vocab_file_path uncased_L-12_H-768_A-12/vocab.txt --current_dataset ASOTEDataRest15 --data_type common_mil_bert --model_name MILForASOBert --train True --evaluate True --predict False --crf False --position False --same_special_token False --aspect_term_aware True --lstm_layer_num_of_sentiment_specific 0 --sequence_label_attention True --softmax_after_opinion_logit False --validation_metric +opinion_sentiment_f1 --atsa_loss_weight 1 --towe_loss_weight 1 --towe_warmup True > mil_aso.4-ASOTEDataRest15-0.log 2>&1 &

sh repeat_non_bert.sh 7 4-ASOTEDataRest16-0,4-ASOTEDataRest16-1,4-ASOTEDataRest16-2,4-ASOTEDataRest16-3,4-ASOTEDataRest16-4 nlp_tasks/absa/mining_opinions/sequence_labeling/aso_bootstrap.py --embedding_filepath glove.840B.300d.txt --bert_file_path bert-base-uncased.tar.gz --bert_vocab_file_path uncased_L-12_H-768_A-12/vocab.txt --current_dataset ASOTEDataRest16 --data_type common_mil_bert --model_name MILForASOBert --train True --evaluate True --predict False --crf False --position False --same_special_token False --aspect_term_aware True --lstm_layer_num_of_sentiment_specific 0 --sequence_label_attention True --softmax_after_opinion_logit False --validation_metric +opinion_sentiment_f1  --atsa_loss_weight 1 --towe_loss_weight 1 --towe_warmup True > mil_aso.4-ASOTEDataRest16-0.log 2>&1 &

# 10
sh repeat_non_bert.sh 3 10-ASOTEDataRest14-0,10-ASOTEDataRest14-1,10-ASOTEDataRest14-2,10-ASOTEDataRest14-3,10-ASOTEDataRest14-4 nlp_tasks/absa/mining_opinions/sequence_labeling/aso_bootstrap.py --embedding_filepath glove.840B.300d.txt --bert_file_path bert-base-uncased.tar.gz --bert_vocab_file_path uncased_L-12_H-768_A-12/vocab.txt --current_dataset ASOTEDataRest14 --data_type common_mil_bert --model_name MILForASOBert --train True --evaluate True --predict False --crf False --position False --same_special_token False --aspect_term_aware True --lstm_layer_num_of_sentiment_specific 0 --sequence_label_attention True --softmax_after_opinion_logit False --validation_metric +opinion_sentiment_f1 --atsa_loss_weight 1 --towe_loss_weight 1 --towe_warmup True --fixed_bert False --batch_size 64 --patience 5 > mil_aso.10-ASOTEDataRest14-0.log 2>&1 &

sh repeat_non_bert.sh 3 10-ASOTEDataLapt14-0,10-ASOTEDataLapt14-1,10-ASOTEDataLapt14-2,10-ASOTEDataLapt14-3,10-ASOTEDataLapt14-4 nlp_tasks/absa/mining_opinions/sequence_labeling/aso_bootstrap.py --embedding_filepath glove.840B.300d.txt --bert_file_path bert-base-uncased.tar.gz --bert_vocab_file_path uncased_L-12_H-768_A-12/vocab.txt --current_dataset ASOTEDataLapt14 --data_type common_mil_bert --model_name MILForASOBert --train True --evaluate True --predict False --crf False --position False --same_special_token False --aspect_term_aware True --lstm_layer_num_of_sentiment_specific 0 --sequence_label_attention True --softmax_after_opinion_logit False --validation_metric +opinion_sentiment_f1 --atsa_loss_weight 1 --towe_loss_weight 1 --towe_warmup True --fixed_bert False --batch_size 64 --patience 5 > mil_aso.10-ASOTEDataLapt14-0.log 2>&1 &

sh repeat_non_bert.sh 3 10-ASOTEDataRest15-0,10-ASOTEDataRest15-1,10-ASOTEDataRest15-2,10-ASOTEDataRest15-3,10-ASOTEDataRest15-4 nlp_tasks/absa/mining_opinions/sequence_labeling/aso_bootstrap.py --embedding_filepath glove.840B.300d.txt --bert_file_path bert-base-uncased.tar.gz --bert_vocab_file_path uncased_L-12_H-768_A-12/vocab.txt --current_dataset ASOTEDataRest15 --data_type common_mil_bert --model_name MILForASOBert --train True --evaluate True --predict False --crf False --position False --same_special_token False --aspect_term_aware True --lstm_layer_num_of_sentiment_specific 0 --sequence_label_attention True --softmax_after_opinion_logit False --validation_metric +opinion_sentiment_f1 --atsa_loss_weight 1 --towe_loss_weight 1 --towe_warmup True --fixed_bert False --batch_size 64 --patience 5 > mil_aso.10-ASOTEDataRest15-0.log 2>&1 &

sh repeat_non_bert.sh 3 10-ASOTEDataRest16-0,10-ASOTEDataRest16-1,10-ASOTEDataRest16-2,10-ASOTEDataRest16-3,10-ASOTEDataRest16-4 nlp_tasks/absa/mining_opinions/sequence_labeling/aso_bootstrap.py --embedding_filepath glove.840B.300d.txt --bert_file_path bert-base-uncased.tar.gz --bert_vocab_file_path uncased_L-12_H-768_A-12/vocab.txt --current_dataset ASOTEDataRest16 --data_type common_mil_bert --model_name MILForASOBert --train True --evaluate True --predict False --crf False --position False --same_special_token False --aspect_term_aware True --lstm_layer_num_of_sentiment_specific 0 --sequence_label_attention True --softmax_after_opinion_logit False --validation_metric +opinion_sentiment_f1  --atsa_loss_weight 1 --towe_loss_weight 1 --towe_warmup True --fixed_bert False --batch_size 64 --patience 5 > mil_aso.10-ASOTEDataRest16-0.log 2>&1 &
