# towe
# 0
sh repeat_non_bert.sh 0 0-ASOTEDataRest14-0,0-ASOTEDataRest14-1,0-ASOTEDataRest14-2,0-ASOTEDataRest14-3,0-ASOTEDataRest14-4 nlp_tasks/absa/mining_opinions/sequence_labeling/towe_bootstrap.py --embedding_filepath glove.840B.300d.txt --current_dataset ASOTEDataRest14 --data_type common --model_name TermBiLSTM --train True --evaluate True --predict False --crf False --position False --same_special_token False > towe.0-ASOTEDataRest14-0.log 2>&1 &

sh repeat_non_bert.sh 0 0-ASOTEDataLapt14-0,0-ASOTEDataLapt14-1,0-ASOTEDataLapt14-2,0-ASOTEDataLapt14-3,0-ASOTEDataLapt14-4 nlp_tasks/absa/mining_opinions/sequence_labeling/towe_bootstrap.py --embedding_filepath glove.840B.300d.txt --current_dataset ASOTEDataLapt14 --data_type common --model_name TermBiLSTM --train True --evaluate True --predict False --crf False --position False --same_special_token False > towe.0-ASOTEDataLapt14-0.log 2>&1 &

sh repeat_non_bert.sh 0 0-ASOTEDataRest15-0,0-ASOTEDataRest15-1,0-ASOTEDataRest15-2,0-ASOTEDataRest15-3,0-ASOTEDataRest15-4 nlp_tasks/absa/mining_opinions/sequence_labeling/towe_bootstrap.py --embedding_filepath glove.840B.300d.txt --current_dataset ASOTEDataRest15 --data_type common --model_name TermBiLSTM --train True --evaluate True --predict False --crf False --position False --same_special_token False > towe.0-ASOTEDataRest15-0.log 2>&1 &

sh repeat_non_bert.sh 0 0-ASOTEDataRest16-0,0-ASOTEDataRest16-1,0-ASOTEDataRest16-2,0-ASOTEDataRest16-3,0-ASOTEDataRest16-4 nlp_tasks/absa/mining_opinions/sequence_labeling/towe_bootstrap.py --embedding_filepath glove.840B.300d.txt --current_dataset ASOTEDataRest16 --data_type common --model_name TermBiLSTM --train True --evaluate True --predict False --crf False --position False --same_special_token False > towe.0-ASOTEDataRest16-0.log 2>&1 &

# 2
sh repeat_non_bert.sh 2 2-ASOTEDataRest14-0,2-ASOTEDataRest14-1,2-ASOTEDataRest14-2,2-ASOTEDataRest14-3,2-ASOTEDataRest14-4 nlp_tasks/absa/mining_opinions/sequence_labeling/towe_bootstrap.py --embedding_filepath glove.840B.300d.txt --bert_file_path bert-base-uncased.tar.gz --bert_vocab_file_path uncased_L-12_H-768_A-12/vocab.txt --current_dataset ASOTEDataRest14 --data_type common_bert --model_name TermBert --train True --evaluate True --predict False --crf False --same_special_token False > towe.2-ASOTEDataRest14-0.log 2>&1 &

sh repeat_non_bert.sh 2 2-ASOTEDataLapt14-0,2-ASOTEDataLapt14-1,2-ASOTEDataLapt14-2,2-ASOTEDataLapt14-3,2-ASOTEDataLapt14-4 nlp_tasks/absa/mining_opinions/sequence_labeling/towe_bootstrap.py --embedding_filepath glove.840B.300d.txt --bert_file_path bert-base-uncased.tar.gz --bert_vocab_file_path uncased_L-12_H-768_A-12/vocab.txt --current_dataset ASOTEDataLapt14 --data_type common_bert --model_name TermBert --train True --evaluate True --predict False --crf False --same_special_token False > towe.2-ASOTEDataLapt14-0.log 2>&1 &

sh repeat_non_bert.sh 2 2-ASOTEDataRest15-0,2-ASOTEDataRest15-1,2-ASOTEDataRest15-2,2-ASOTEDataRest15-3,2-ASOTEDataRest15-4 nlp_tasks/absa/mining_opinions/sequence_labeling/towe_bootstrap.py --embedding_filepath glove.840B.300d.txt --bert_file_path bert-base-uncased.tar.gz --bert_vocab_file_path uncased_L-12_H-768_A-12/vocab.txt --current_dataset ASOTEDataRest15 --data_type common_bert --model_name TermBert --train True --evaluate True --predict False --crf False --same_special_token False > towe.2-ASOTEDataRest15-0.log 2>&1 &

sh repeat_non_bert.sh 2 2-ASOTEDataRest16-0,2-ASOTEDataRest16-1,2-ASOTEDataRest16-2,2-ASOTEDataRest16-3,2-ASOTEDataRest16-4 nlp_tasks/absa/mining_opinions/sequence_labeling/towe_bootstrap.py --embedding_filepath glove.840B.300d.txt --bert_file_path bert-base-uncased.tar.gz --bert_vocab_file_path uncased_L-12_H-768_A-12/vocab.txt --current_dataset ASOTEDataRest16 --data_type common_bert --model_name TermBert --train True --evaluate True --predict False --crf False --same_special_token False > towe.2-ASOTEDataRest16-0.log 2>&1 &

# 8
sh repeat_non_bert.sh 0 8-ASOTEDataRest14-0,8-ASOTEDataRest14-1,8-ASOTEDataRest14-2,8-ASOTEDataRest14-3,8-ASOTEDataRest14-4 nlp_tasks/absa/mining_opinions/sequence_labeling/towe_bootstrap.py --embedding_filepath glove.840B.300d.txt --bert_file_path bert-base-uncased.tar.gz --bert_vocab_file_path uncased_L-12_H-768_A-12/vocab.txt --current_dataset ASOTEDataRest14 --data_type common_bert --model_name TermBert --train True --evaluate True --predict False --crf False --same_special_token False --fixed_bert False > towe.8-ASOTEDataRest14-0.log 2>&1 &

sh repeat_non_bert.sh 1 8-ASOTEDataLapt14-0,8-ASOTEDataLapt14-1,8-ASOTEDataLapt14-2,8-ASOTEDataLapt14-3,8-ASOTEDataLapt14-4 nlp_tasks/absa/mining_opinions/sequence_labeling/towe_bootstrap.py --embedding_filepath glove.840B.300d.txt --bert_file_path bert-base-uncased.tar.gz --bert_vocab_file_path uncased_L-12_H-768_A-12/vocab.txt --current_dataset ASOTEDataLapt14 --data_type common_bert --model_name TermBert --train True --evaluate True --predict False --crf False --same_special_token False --fixed_bert False > towe.8-ASOTEDataLapt14-0.log 2>&1 &

sh repeat_non_bert.sh 2 8-ASOTEDataRest15-0,8-ASOTEDataRest15-1,8-ASOTEDataRest15-2,8-ASOTEDataRest15-3,8-ASOTEDataRest15-4 nlp_tasks/absa/mining_opinions/sequence_labeling/towe_bootstrap.py --embedding_filepath glove.840B.300d.txt --bert_file_path bert-base-uncased.tar.gz --bert_vocab_file_path uncased_L-12_H-768_A-12/vocab.txt --current_dataset ASOTEDataRest15 --data_type common_bert --model_name TermBert --train True --evaluate True --predict False --crf False --same_special_token False --fixed_bert False > towe.8-ASOTEDataRest15-0.log 2>&1 &

sh repeat_non_bert.sh 3 8-ASOTEDataRest16-0,8-ASOTEDataRest16-1,8-ASOTEDataRest16-2,8-ASOTEDataRest16-3,8-ASOTEDataRest16-4 nlp_tasks/absa/mining_opinions/sequence_labeling/towe_bootstrap.py --embedding_filepath glove.840B.300d.txt --bert_file_path bert-base-uncased.tar.gz --bert_vocab_file_path uncased_L-12_H-768_A-12/vocab.txt --current_dataset ASOTEDataRest16 --data_type common_bert --model_name TermBert --train True --evaluate True --predict False --crf False --same_special_token False --fixed_bert False > towe.8-ASOTEDataRest16-0.log 2>&1 &